name: TEST Update native SDKs and create a pull request if necessary

on:
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Find the latest Android SDK version and update build.gradle file
        run: |
          COBROWSE_VERSION=$(wget -O - -o /dev/null https://raw.githubusercontent.com/cobrowseio/cobrowse-sdk-android-binary/master/io/cobrowse/cobrowse-sdk-android/maven-metadata.xml | grep -Eo '<version>[0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?</version>' | grep -Eo '([0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?)' | sort --version-sort -r | head -n 1)
          sed -i '.bak' "s/\(io\.cobrowse\:cobrowse-sdk-android\:\).*/\\1${COBROWSE_VERSION}'/" android/build.gradle
      - name:
        run: |
          COBROWSE_VERSION=$(wget -O - -o /dev/null https://raw.githubusercontent.com/cobrowseio/cobrowse-sdk-ios-binary/master/CobrowseIO.podspec | grep -Eo "s\.version\ +=\ +'[0-9]+\.[0-9]+\.[0-9]+'" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          sed -i '.bak' "s/\(s\.dependency\ *'CobrowseIO\/XCFramework'\,\ *'\).*/\\1${COBROWSE_VERSION}'/" cobrowse-sdk-react-native.podspec
      - name: cat android/build.gradle
        run: cat android/build.gradle
      - name: cat cobrowse-sdk-react-native.podspec
        run: cat cobrowse-sdk-react-native.podspec
